### ISSUE TITLE
[Feature request] Allow instance creation with no running event loop

### ISSUE THREAD

**Issue by prryplatypus** [ahopkins/mayim#12]
Currently when creating a Mayim instance, an event loop must already be running, or otherwise an exception is raised. I imagine this is because Mayim handles the connection and disconnection from the database automatically, which usually requires calling asynchronous functions.

My suggestion would be that Mayim allows creation of an instance without an event loop running yet, and that the connection and disconnection can be done manually when required. This would allow usecases such as the following, where `mayim` can be placed in a separate module that can be imported before there is an existing loop running.

```py
from sanic import Sanic
from mayim import Mayim

app = Sanic(__name__)
mayim = Mayim(dsn=...)

@app.before_server_start
async def connect_database(*_):
    await mayim.connect()

@app.after_server_stop
async def disconnect_database(*_):
    await mayim.disconnect()

...
```

**Comment by ahopkins** [comment]
That is indeed a limitation with psycopg. We would need to come up with some sort of context-aware/lazy holder.

**Comment by ahopkins** [comment]
This will actually be something that gets added when I tackle #10.
