### ISSUE TITLE
Is mysql.interface line 70 supposed to be not transaction?

### ISSUE THREAD

**Issue by xxxzc** [ahopkins/mayim#46]
Mysql executor does not commit after executing update sql, is mysql.interface line 70 supposed to be `not transaction`?
https://github.com/ahopkins/mayim/blob/c73d9d2d12c1c77d63e6ef827ace8032768b2271/src/mayim/sql/mysql/interface.py#L64-L72

After changing to not transaction, the update was committed normally

**Comment by ahopkins** [comment]
Are you trying to use it in a transaction or not?

**Comment by michaeljduncan** [comment]
Having similar issue. SELECT statements work fine, but an UPDATE statement will not commit unless I set `transaction = True`.  How do you execute an UPDATE statement that is not in a transaction?

**Comment by adk23333** [comment]
`INSERT` also has this problem.

The operation of writing strings to MySQL requires adding '', for example: `INSERT ... VALUS (123, 'abc')`

**Comment by adk23333** [comment]
I have discovered the cause of the problem,After the execute statement is completed, the commit method of the connect object needs to be called.He didn't do it here.

**Comment by adk23333** [comment]
https://github.com/ahopkins/mayim/issues/53#issuecomment-1821432156

@slipstream77 

This should be done

> Are you trying to use it in a transaction or not?
